SELECT 
  COUNT(*) AS Total_Filas,

  -- Clientes
  SUM(CASE WHEN c.Edad IS NULL THEN 1 ELSE 0 END) AS Edad_Nula,
  SUM(CASE WHEN c.RENTA_MEDIA_ESTIMADA IS NULL THEN 1 ELSE 0 END) AS Renta_Media_Estimada_Nula,
  SUM(CASE WHEN c.ENCUESTA_ZONA_CLIENTE_VENTA IS NULL THEN 1 ELSE 0 END) AS Encuesta_Zona_Cliente_Venta_Nula,
  SUM(CASE WHEN c.ENCUESTA_CLIENTE_ZONA_TALLER IS NULL THEN 1 ELSE 0 END) AS Encuesta_Cliente_Zona_Taller_Nula,
  SUM(CASE WHEN c.GENERO IS NULL THEN 1 ELSE 0 END) AS Genero_Nulo,
  SUM(CASE WHEN c.CODIGO_POSTAL IS NULL THEN 1 ELSE 0 END) AS Codigo_Postal_Nulo,
  SUM(CASE WHEN c.Fecha_nacimiento IS NULL THEN 1 ELSE 0 END) AS Fecha_Nacimiento_Nula,
  SUM(CASE WHEN c.STATUS_SOCIAL IS NULL THEN 1 ELSE 0 END) AS Status_Social_Nulo,

  -- Código Postal
  SUM(CASE WHEN cp.provincia IS NULL THEN 1 ELSE 0 END) AS Provincia_Nula,
  SUM(CASE WHEN cp.poblacion IS NULL THEN 1 ELSE 0 END) AS Poblacion_Nula,
  SUM(CASE WHEN cp.lat IS NULL THEN 1 ELSE 0 END) AS Latitud_Nula,
  SUM(CASE WHEN cp.lon IS NULL THEN 1 ELSE 0 END) AS Longitud_Nula,

  -- Mosaic
  SUM(CASE WHEN m.U IS NULL THEN 1 ELSE 0 END) AS Mosaic_U_Nulo,
  SUM(CASE WHEN m.Max_Mosaic IS NULL THEN 1 ELSE 0 END) AS Max_Mosaic_Nulo,
  SUM(CASE WHEN m.Renta_Media IS NULL THEN 1 ELSE 0 END) AS Renta_Media_Mosaic_Nula

  -- Puedes seguir añadiendo más columnas si lo necesitas...

FROM [DATAEX].[003_clientes] c
LEFT JOIN [DATAEX].[005_cp] cp 
    ON c.CODIGO_POSTAL = cp.CP
LEFT JOIN [DATAEX].[019_Mosaic] m
    ON cp.CP = CONCAT('CP', CAST(m.CP AS VARCHAR(10)));

SELECT 
  COUNT(*) AS Total_Filas,

  -- SALES
  SUM(CASE WHEN S.CODE IS NULL THEN 1 ELSE 0 END) AS CODE_Nulos,
  SUM(CASE WHEN S.Code_ IS NULL THEN 1 ELSE 0 END) AS Code__Nulos,
  SUM(CASE WHEN S.Customer_ID IS NULL THEN 1 ELSE 0 END) AS Customer_ID_Nulos,
  SUM(CASE WHEN S.Id_Producto IS NULL THEN 1 ELSE 0 END) AS Id_Producto_Nulos,
  SUM(CASE WHEN S.TIENDA_ID IS NULL THEN 1 ELSE 0 END) AS TIENDA_ID_Nulos,
  SUM(CASE WHEN S.MOTIVO_VENTA_ID IS NULL THEN 1 ELSE 0 END) AS MOTIVO_VENTA_ID_Nulos,
  SUM(CASE WHEN S.FORMA_PAGO_ID IS NULL THEN 1 ELSE 0 END) AS FORMA_PAGO_ID_Nulos,
  SUM(CASE WHEN S.Sales_Date IS NULL THEN 1 ELSE 0 END) AS Sales_Date_Nulos,
  SUM(CASE WHEN S.PVP IS NULL THEN 1 ELSE 0 END) AS PVP_Nulos,
  SUM(CASE WHEN S.SEGURO_BATERIA_LARGO_PLAZO IS NULL THEN 1 ELSE 0 END) AS Seguro_Bateria_Nulos,
  SUM(CASE WHEN S.MANTENIMIENTO_GRATUITO IS NULL THEN 1 ELSE 0 END) AS Mantenimiento_Gratuito_Nulos,
  SUM(CASE WHEN S.FIN_GARANTIA IS NULL THEN 1 ELSE 0 END) AS Fin_Garantia_Nulos,
  SUM(CASE WHEN S.COSTE_VENTA_NO_IMPUESTOS IS NULL THEN 1 ELSE 0 END) AS Coste_Venta_Nulos,
  SUM(CASE WHEN S.IMPUESTOS IS NULL THEN 1 ELSE 0 END) AS Impuestos_Nulos,
  SUM(CASE WHEN S.EXTENSION_GARANTIA IS NULL THEN 1 ELSE 0 END) AS Extension_Garantia_Nulos,
  SUM(CASE WHEN S.BASE_DATE IS NULL THEN 1 ELSE 0 END) AS Base_Date_Nulos,
  SUM(CASE WHEN S.EN_GARANTIA IS NULL THEN 1 ELSE 0 END) AS En_Garantia_Nulos,

  -- FORMA DE PAGO
  SUM(CASE WHEN FP.FORMA_PAGO IS NULL THEN 1 ELSE 0 END) AS Forma_Pago_Nulos,
  SUM(CASE WHEN FP.FORMA_PAGO_GRUPO IS NULL THEN 1 ELSE 0 END) AS Forma_Pago_Grupo_Nulos,

  -- LOGÍSTICA
  SUM(CASE WHEN L.Fue_Lead IS NULL THEN 1 ELSE 0 END) AS Fue_Lead_Nulos,
  SUM(CASE WHEN L.Lead_compra IS NULL THEN 1 ELSE 0 END) AS Lead_Compra_Nulos,
  SUM(CASE WHEN L.t_prod_date IS NULL THEN 1 ELSE 0 END) AS T_Prod_Date_Nulos,
  SUM(CASE WHEN L.t_logist_days IS NULL THEN 1 ELSE 0 END) AS T_Logist_Days_Nulos,
  SUM(CASE WHEN L.t_stock_dates IS NULL THEN 1 ELSE 0 END) AS T_Stock_Dates_Nulos,
  SUM(CASE WHEN L.Prod_date IS NULL THEN 1 ELSE 0 END) AS Prod_Date_Nulos,
  SUM(CASE WHEN L.Logistic_date IS NULL THEN 1 ELSE 0 END) AS Logistic_Date_Nulos,
  SUM(CASE WHEN L.Origen_Compra_ID IS NULL THEN 1 ELSE 0 END) AS Origen_Compra_ID_Nulos,

  -- ORIGEN VENTA
  SUM(CASE WHEN OV.Origen IS NULL THEN 1 ELSE 0 END) AS Origen_Nulos,

  -- REVISIONES
  SUM(CASE WHEN R.Revisiones IS NULL THEN 1 ELSE 0 END) AS Revisiones_Nulos,
  SUM(CASE WHEN R.Km_medio_por_revision IS NULL THEN 1 ELSE 0 END) AS Km_Medio_Por_Revision_Nulos,
  SUM(CASE WHEN R.km_ultima_revision IS NULL THEN 1 ELSE 0 END) AS Km_Ultima_Revision_Nulos,
  SUM(CASE WHEN R.DIAS_DESDE_ULTIMA_REVISION IS NULL THEN 1 ELSE 0 END) AS Dias_Desde_Ultima_Revision_Nulos,
  SUM(CASE 
      WHEN R.DATE_UTIMA_REV IS NULL OR LTRIM(RTRIM(R.DATE_UTIMA_REV)) = '' THEN 1 
      ELSE 0 
  END) AS Fecha_Ultima_Revision_Nulos,

  -- CAC
  SUM(CASE WHEN C.DIAS_EN_TALLER IS NULL THEN 1 ELSE 0 END) AS Dias_En_Taller_Nulos,
  SUM(CASE WHEN C.DIAS_DESDE_LA_ULTIMA_ENTRADA_TALLER IS NULL THEN 1 ELSE 0 END) AS Dias_Desde_Ultima_Entrada_Nulos,
  SUM(CASE WHEN C.QUEJA IS NULL THEN 1 ELSE 0 END) AS Queja_Nulos,

  -- EDAD DEL COCHE
  SUM(CASE WHEN E.Car_Age IS NULL THEN 1 ELSE 0 END) AS Car_Age_Nulos,

  -- COSTES (MÉTRICAS)
  SUM(CASE WHEN COST.Margen IS NULL THEN 1 ELSE 0 END) AS Margen_Nulos,
  SUM(CASE WHEN COST.Margendistribuidor IS NULL THEN 1 ELSE 0 END) AS Margen_Distribuidor_Nulos,
  SUM(CASE WHEN COST.GastosMarketing IS NULL THEN 1 ELSE 0 END) AS Gastos_Marketing_Nulos,
  SUM(CASE WHEN COST.Comisión_Marca IS NULL THEN 1 ELSE 0 END) AS Comision_Marca_Nulos,
  SUM(CASE WHEN COST.Costetransporte IS NULL THEN 1 ELSE 0 END) AS Coste_Transporte_Nulos

FROM [DATAEX].[001_sales] S
LEFT JOIN [DATAEX].[010_forma_pago] FP ON S.FORMA_PAGO_ID = FP.FORMA_PAGO_ID
LEFT JOIN [DATAEX].[017_logist] L ON S.CODE = L.CODE
LEFT JOIN [DATAEX].[016_origen_venta] OV ON L.Origen_Compra_ID = OV.Origen_Compra_ID
LEFT JOIN [DATAEX].[004_rev] R ON S.CODE = R.CODE
LEFT JOIN [DATAEX].[008_cac] C ON S.CODE = C.CODE
LEFT JOIN [DATAEX].[018_edad] E ON S.CODE = E.CODE
LEFT JOIN [DATAEX].[009_motivo_venta] MV ON S.MOTIVO_VENTA_ID = MV.MOTIVO_VENTA_ID
LEFT JOIN [DATAEX].[006_producto] P ON S.Id_Producto = P.Id_Producto
LEFT JOIN [DATAEX].[007_COSTES] COST ON P.Modelo = COST.Modelo



