FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Subimos todo el proyecto al contenedor
COPY ../../ ./

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]